#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Azul\Command\PlayGameCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new PlayGameCommand());

$application->run();